# Generated by Django 3.2.8 on 2021-10-18 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('EmployeeId', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=500)),
                ('EmployeeLastName', models.CharField(max_length=500)),
                ('Department', models.CharField(max_length=500)),
                ('SubArea', models.CharField(max_length=500)),
                ('DocumentType', models.CharField(max_length=500)),
                ('PhotoFileName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SubAreas',
            fields=[
                ('SubAreaId', models.AutoField(primary_key=True, serialize=False)),
                ('SubAreaName', models.CharField(max_length=500)),
                ('Department', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
